server:
  port: 8080

spring:
  application:
    name: demo
  datasource:

    url: jdbc:mariadb://springdb.cnf2esnbu6ka.ap-northeast-2.rds.amazonaws.com:3306/bamin?autoReconnect=true
    # url 형식은 jdbc:mysql://RDS의 EndPoint/내부 DB 스키마명 입니다.
    username: admin # 만약 따로 설정하지 않으셨다면 기본값은 admin 입니다
    password: qwerty123 # 비밀번호를 입력해주세요!
    driver-class-name: org.mariadb.jdbc.Driver

